# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=256)),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='StoryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_text', models.CharField(max_length=1024)),
                ('contributer', models.CharField(max_length=128)),
                ('date_published', models.DateTimeField(verbose_name='published')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='sentences',
            field=models.ManyToManyField(to='story.StoryLine'),
        ),
    ]
